name: CDN Test
on: workflow_dispatch

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.CDN_PRIVATE_KEY }}
      - run: ./scripts/cdn.sh
