name: Deploy Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  Release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - uses: jonsnyder/project-card-release-automation/validate-version@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ github.event.inputs.version }}
      - uses: actions/checkout@v2
      - name: Update Version
        run: |
          npm run ci
          npm run test
          # setup configuration
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
          git remote add gh-origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git/
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          # update version in package.json and package-lock.json
          npm version ${{ github.event.inputs.version }} --git-tag-version=false
          git add package.json package-lock.json
          git commit -m "${{ github.event.inputs.version }}"
          # publish the package to NPM
          npm publish --access public
          # update reference to NPM version
          npm install @jonsnyder01/increment@${{ github.event.inputs.version }} --save-dev
          git add package.json package-lock.json
          # tag and push the release
          git tag -a "v${{ github.event.inputs.version }}"
          git push gh-origin HEAD:${GITHUB_REF}
      - uses: jonsnyder/project-card-release-automation/record-release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ github.event.inputs.version }}