name: Deploy Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  Release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Release Version
        run: |
          cd scripts
          npm ci
          ./bin/validateReleaseVersion.js ${{ github.event.inputs.version }}
      - name: Update Version
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
          git remote add gh-origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git/
          npx semver ${{ github.event.inputs.version }}
          npm version ${{ github.event.inputs.version }}
          git push gh-origin HEAD:main --tags