name: Deploy Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  approval:
    name: "Approval"
    environment: Deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "Approved"
  release:
    name: "Release"
    runs-on: ubuntu-latest
    needs: approval
    steps:
      - uses: jonsnyder/project-card-release-automation/validate-version@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ github.event.inputs.version }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Update Version
        run: |
          # install dependencies
          npm ci
          # run tests
          npm run test
          # setup configuration
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
          git remote add gh-origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git/
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          # update version in package.json and package-lock.json
          npm version ${{ github.event.inputs.version }} --git-tag-version=false
          git add package.json package-lock.json
          git commit -m "${{ github.event.inputs.version }}"
          # publish the package to NPM if it hasn't already been published
          if [[ -z "$(npm view @jonsnyder01/increment@${{ github.event.inputs.version }})" ]]; then
            echo "Publishing to NPM"
            npm publish --access public
          else
            echo "NPM already has version ${{ github.event.inputs.version }}"
          fi
          # update reference to NPM version
          npm install @jonsnyder01/increment@${{ github.event.inputs.version }} --save-dev
          git add package.json package-lock.json
          # tag and push the release
          git commit -m "update self devDependency to ${{ github.event.inputs.version }}"
          git tag -a "v${{ github.event.inputs.version }}" -m "${{ github.event.inputs.version }}"
          git push gh-origin HEAD:${GITHUB_REF} --follow-tags
      - uses: jonsnyder/project-card-release-automation/record-release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ github.event.inputs.version }}