name: Deploy Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  validate:
    name: "Validate"
    runs-on: ubuntu-latest
    steps:
      - uses: jonsnyder/project-card-release-automation/validate-version@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ github.event.inputs.version }}
  approval:
    name: "Approval"
    environment: Deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "Approved"
    if: ${{ contains(github.event.inputs.version, '-') == false }}
    needs: validate
  release:
    name: "Release"
    runs-on: ubuntu-latest
    needs: approval
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: ./scripts/deploy.sh ${{ github.event.inputs.version }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: jonsnyder/project-card-release-automation/record-release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ github.event.inputs.version }}
  prerelease:
    name: "Prerelease"
    runs-on: ubuntu-latest
    needs: validate
    if: ${{ contains(gitub.event.inputs.version, '-') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: ./scripts/deploy.sh ${{ github.event.inputs.version }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: jonsnyder/project-card-release-automation/record-release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ github.event.inputs.version }}