name: Initialize Intended Release
on:
  workflow_dispatch:
    inputs:
      type:
        description: "Release Type [major|minor|patch]"
        required: true

jobs:
  initializeIntendedRelease:
    name: "Initialize Intended Release"
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Intended Release
        uses: jonsnyder/project-card-release-automation@main
        with:
          releaseType: ${{ github.event.inputs.type }}
          command: initialize-card
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}