name: Initialize Intended Release
on:
  workflow_dispatch:
    inputs:
      type:
        description: "Release Type [major|minor|patch]"
        required: true

jobs:
  initializeIntendedRelease:
    name: "Initialize Intended Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - run: ./scripts/initializeIntendedRelease.js ${{ github.event.inputs.type }}
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}