name: Trigger Release
on:
  project_card:
    types: [moved]
  push:
    branch:
      - main
      - "v[0-9]+"
      - "v[0-9]+.[0-9]"
jobs:
  triggerReleaseIfNeeded:
    name: "Trigger Release If Needed"
    runs-on: ubuntu-latest
    steps:
      - uses: jonsnyder/project-card-release-automation/trigger-release@main
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          workflowId: "deployRelease.yml"
          projectNumber: 1